'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, Download, ChevronDown } from 'lucide-react';

interface Props {
  company: string;
  onClose: () => void;
}

type Jurisdiction = 'US_DOL' | 'UK_GLAA' | 'ILO';

const JURISDICTION_LABELS: Record<Jurisdiction, string> = {
  US_DOL: 'US Department of Labor',
  UK_GLAA: 'UK Gangmasters & Labour Abuse Authority',
  ILO: 'International Labour Organization',
};

function buildLetter(company: string, jurisdiction: Jurisdiction): string {
  const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

  const openings: Record<Jurisdiction, string> = {
    US_DOL: `To the Office of Trade and Labour Affairs\nUnited States Department of Labor\nWashington, D.C. 20210`,
    UK_GLAA: `To the Director of Investigations\nGangmasters and Labour Abuse Authority\nScunthorpe, DN15 8QZ`,
    ILO: `To the Director-General\nInternational Labour Organization\nCH-1211 Geneva 22, Switzerland`,
  };

  const statutes: Record<Jurisdiction, string> = {
    US_DOL: 'the Uyghur Forced Labor Prevention Act (UFLPA, P.L. 117-78) and 19 U.S.C. § 1307',
    UK_GLAA: 'the Modern Slavery Act 2015 and the Immigration Act 2016',
    ILO: 'ILO Convention No. 29 (Forced Labour), No. 105 (Abolition of Forced Labour), and No. 182 (Worst Forms of Child Labour)',
  };

  return `${date}

${openings[jurisdiction]}

RE: Formal Complaint — Suspected Labour Exploitation in ${company}'s Supply Chain

Dear Sir or Madam,

I write on behalf of concerned researchers and civil society to bring to your urgent attention credible evidence of serious labour rights violations across the supply chain of ${company}, a fast-fashion retailer with global operations.

Our investigation, conducted using open-source intelligence, satellite imagery analysis, corporate disclosure review, and cross-referencing of sanctions watchlists, has identified the following material concerns under ${statutes[jurisdiction]}:

1. XINJIANG FORCED LABOUR EXPOSURE
   ${company} sources cotton-based textiles from Xinjiang Cotton Processors, an entity listed on the UFLPA Entity List maintained by the Forced Labor Enforcement Task Force. Under the UFLPA's rebuttable presumption standard, all goods produced in whole or in part with labour from the Xinjiang Uyghur Autonomous Region are presumed to have been manufactured with forced labour.

2. MYANMAR MILITARY-LINKED SUPPLIER
   The facility known as Yangon Sewing Works has been credibly linked to the Myanmar Economic Holdings Limited (MEHL), a military conglomerate subject to US OFAC sanctions. Continued commercial relationships with MEHL-affiliated entities may constitute violations of US Executive Order 14014 and UK sanctions under the Myanmar (Sanctions) Regulations 2021.

3. MATERIAL MISREPRESENTATION IN MODERN SLAVERY STATEMENT
   ${company}'s most recent Modern Slavery Act § 54 statement omits four of six identified high-risk supply chain nodes, constituting a material failure of transparency that may amount to a criminal offence under section 54(11) of the Modern Slavery Act 2015.

4. INADEQUATE HEALTH & SAFETY COMPLIANCE
   Workers at Dhaka Garment Mills Ltd. (Bangladesh) — a verified tier-1 supplier — face severe fire-safety hazards. Three consecutive audits (2022–2024) have documented non-compliance with International Finance Corporation Performance Standard 2 and the Bangladesh National Building Code.

We respectfully request that your office:
(a) Open a formal investigation into the above allegations;
(b) Require ${company} to provide a full and accurate supply chain disclosure within 30 days;
(c) Consider enforcement action, including import restrictions and civil penalties, where appropriate.

Supporting documentation including audit reports, satellite evidence, financial linkage analysis, and watchlist cross-references is available upon request.

Yours faithfully,

Lumina Labour Exploitation Research Platform
research@lumina-project.org
https://lumina-project.org

— Generated by Lumina AI Research Tool —
`;
}

export default function ComplaintModal({ company, onClose }: Props) {
  const [jurisdiction, setJurisdiction] = useState<Jurisdiction>('US_DOL');
  const [showJurisdictionMenu, setShowJurisdictionMenu] = useState(false);
  const letter = buildLetter(company, jurisdiction);

  const handleDownload = () => {
    const blob = new Blob([letter], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `complaint-letter-${company.toLowerCase().replace(/\s+/g, '-')}-${jurisdiction}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 z-50 flex items-end justify-center"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
      >
        {/* Backdrop */}
        <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />

        {/* Modal panel */}
        <motion.div
          className="liquid-glass relative z-10 w-full max-w-3xl rounded-t-3xl p-6 flex flex-col"
          style={{ maxHeight: '85vh' }}
          initial={{ y: '100%' }}
          animate={{ y: 0 }}
          exit={{ y: '100%' }}
          transition={{ type: 'spring', stiffness: 280, damping: 32 }}
        >
          {/* Header */}
          <div className="flex items-center justify-between mb-4 flex-shrink-0">
            <div>
              <h2 className="text-white font-medium text-lg">Complaint Letter</h2>
              <p className="text-white/50 text-sm">Formal regulatory complaint — {company}</p>
            </div>
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center hover:bg-white/20 transition-colors"
            >
              <X size={14} className="text-white" />
            </button>
          </div>

          {/* Jurisdiction selector */}
          <div className="relative mb-4 flex-shrink-0">
            <button
              onClick={() => setShowJurisdictionMenu((v) => !v)}
              className="liquid-glass rounded-xl px-4 py-2.5 flex items-center gap-2 text-sm text-white w-full justify-between"
            >
              <span>{JURISDICTION_LABELS[jurisdiction]}</span>
              <ChevronDown
                size={14}
                className="text-white/50 transition-transform duration-200"
                style={{ transform: showJurisdictionMenu ? 'rotate(180deg)' : 'rotate(0deg)' }}
              />
            </button>
            {showJurisdictionMenu && (
              <motion.div
                initial={{ opacity: 0, y: -6 }}
                animate={{ opacity: 1, y: 0 }}
                className="liquid-glass absolute top-full mt-1 left-0 right-0 rounded-xl overflow-hidden z-10"
              >
                {(Object.keys(JURISDICTION_LABELS) as Jurisdiction[]).map((j) => (
                  <button
                    key={j}
                    onClick={() => { setJurisdiction(j); setShowJurisdictionMenu(false); }}
                    className="w-full text-left px-4 py-2.5 text-sm text-white hover:bg-white/10 transition-colors"
                  >
                    {JURISDICTION_LABELS[j]}
                  </button>
                ))}
              </motion.div>
            )}
          </div>

          {/* Letter content */}
          <div className="flex-1 overflow-y-auto rounded-xl bg-white/5 p-4 min-h-0">
            <pre className="text-white/80 text-xs leading-relaxed font-mono whitespace-pre-wrap">
              {letter}
            </pre>
          </div>

          {/* Download button */}
          <button
            onClick={handleDownload}
            className="liquid-glass mt-4 flex-shrink-0 flex items-center justify-center gap-2 px-6 py-3 rounded-2xl text-white font-medium hover:bg-white/10 transition-colors"
          >
            <Download size={16} />
            Download as Text File
          </button>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
