"""Demographic + economic cluster model.

Answers "show me other countries with similar conditions to country X"
using KMeans over standardized demographic + economic features.

Design changes vs the original synthetic-era version:

  - The Gaussian Naive Bayes that predicted a per-country "dominant
    exploit type" was REMOVED. Its target was the per-country argmax
    over four exploit-type prevalences, and those prevalences were
    generated by the synthetic data process from the same features
    that fed the NB → target leakage by construction. With real data
    we only have a single per-country prevalence (GSI), so the NB has
    nothing meaningful to classify.

  - Governance / migration / help blocks are empty in the GSI+WDI+RSF
    data tier, so the cluster collapses to demographic + economic
    similarity. The README's promise was always
    "demographic/economic/migration/help" — without governance — and
    on real data that's now literally what runs.

KMeans picks k by sweeping k = 3..8 and selecting the highest
silhouette score.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

from ..data.real import (
    DEMOGRAPHIC_COLS,
    ECONOMIC_COLS,
    GOVERNANCE_COLS,
    HELP_COLS,
    MIGRATION_COLS,
)


# In the GSI+WDI+RSF tier only demographic + economic blocks have
# populated columns. The other blocks remain in the dict so future
# data tiers (WGI for governance, UNHCR for migration) can drop in
# without changing this signature.
DEFAULT_BLOCKS: Dict[str, List[str]] = {
    "demographic": DEMOGRAPHIC_COLS,
    "economic": ECONOMIC_COLS,
    "governance": GOVERNANCE_COLS,
    "migration": MIGRATION_COLS,
    "help": HELP_COLS,
}


def _selected_features(blocks: Dict[str, List[str]]) -> List[str]:
    return [c for cols in blocks.values() for c in cols]


@dataclass
class TrainedClusterModel:
    scaler: StandardScaler
    kmeans: KMeans
    feature_cols: List[str]
    k: int
    silhouette: float
    cluster_centroids: pd.DataFrame
    n_countries: int
    # Kept for back-compat with downstream consumers expecting the
    # field on the dataclass; never populated since the NB was removed.
    cluster_dominant_exploit: Optional[pd.Series] = field(default=None)

    def assign_cluster(self, X: pd.DataFrame) -> np.ndarray:
        return self.kmeans.predict(self.scaler.transform(X[self.feature_cols]))

    def similar_countries(
        self,
        panel: pd.DataFrame,
        target_country: str,
        top_n: int = 5,
    ) -> pd.DataFrame:
        """Other countries in the same cluster, ranked by Euclidean distance."""
        target = panel[panel["country"] == target_country]
        if target.empty:
            return panel.iloc[0:0]

        Xs_all = self.scaler.transform(panel[self.feature_cols])
        Xs_target = self.scaler.transform(target[self.feature_cols])
        cluster_of_target = self.kmeans.predict(Xs_target)[0]
        cluster_of_all = self.kmeans.predict(Xs_all)

        # Compute distances aligned to the full panel index, attach, then
        # filter — otherwise the slice falls out of sync once the target
        # is dropped and the first non-target row inherits distance=0.
        mask = cluster_of_all == cluster_of_target
        candidates = panel[mask].copy().reset_index(drop=True)
        candidates["distance_to_target"] = np.linalg.norm(
            Xs_all[mask] - Xs_target, axis=1
        )
        candidates = candidates[candidates["country"] != target_country]
        return candidates.sort_values("distance_to_target").head(top_n)


def _select_k(X: np.ndarray, k_range: Tuple[int, ...]) -> Tuple[int, float, KMeans]:
    best: Tuple[int, float, KMeans | None] = (k_range[0], -1.0, None)
    for k in k_range:
        km = KMeans(n_clusters=k, n_init=10, random_state=0).fit(X)
        if len(np.unique(km.labels_)) < 2:
            continue
        score = silhouette_score(X, km.labels_)
        if score > best[1]:
            best = (k, score, km)
    return best  # type: ignore[return-value]


def train_cluster_model(
    panel: pd.DataFrame,
    feature_blocks: Optional[Dict[str, List[str]]] = None,
    k_range: Tuple[int, ...] = (3, 4, 5, 6, 7, 8),
    seed: int = 0,
) -> TrainedClusterModel:
    blocks = feature_blocks or DEFAULT_BLOCKS
    feature_cols = _selected_features(blocks)
    if not feature_cols:
        raise ValueError(
            "No cluster features available — all configured feature blocks "
            "are empty. Check data.real.{DEMOGRAPHIC,ECONOMIC,...}_COLS."
        )

    rows = panel.dropna(subset=feature_cols).reset_index(drop=True)
    scaler = StandardScaler().fit(rows[feature_cols])
    Xs = scaler.transform(rows[feature_cols])

    k, sil, km = _select_k(Xs, k_range)

    with_cluster = rows.assign(cluster=km.labels_)
    centroids = with_cluster.groupby("cluster")[feature_cols].mean().round(3)

    return TrainedClusterModel(
        scaler=scaler,
        kmeans=km,
        feature_cols=feature_cols,
        k=k,
        silhouette=float(sil),
        cluster_centroids=centroids,
        n_countries=int(len(rows)),
    )
